/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.new_vcs_conflicts.bubbledata.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.new_vcs_conflicts.bubbledata.Table2ww;

/**
 * Service object for domain model class {@link Table2ww}.
 */
public interface Table2wwService {

    /**
     * Creates a new Table2ww. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table2ww if any.
     *
     * @param table2ww Details of the Table2ww to be created; value cannot be null.
     * @return The newly created Table2ww.
     */
	Table2ww create(@Valid Table2ww table2ww);


	/**
	 * Returns Table2ww by given id if exists.
	 *
	 * @param table2wwId The id of the Table2ww to get; value cannot be null.
	 * @return Table2ww associated with the given table2wwId.
     * @throws EntityNotFoundException If no Table2ww is found.
	 */
	Table2ww getById(Integer table2wwId) throws EntityNotFoundException;

    /**
	 * Find and return the Table2ww by given id if exists, returns null otherwise.
	 *
	 * @param table2wwId The id of the Table2ww to get; value cannot be null.
	 * @return Table2ww associated with the given table2wwId.
	 */
	Table2ww findById(Integer table2wwId);


	/**
	 * Updates the details of an existing Table2ww. It replaces all fields of the existing Table2ww with the given table2ww.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Table2ww if any.
     *
	 * @param table2ww The details of the Table2ww to be updated; value cannot be null.
	 * @return The updated Table2ww.
	 * @throws EntityNotFoundException if no Table2ww is found with given input.
	 */
	Table2ww update(@Valid Table2ww table2ww) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table2ww with the given id.
	 *
	 * @param table2wwId The id of the Table2ww to be deleted; value cannot be null.
	 * @return The deleted Table2ww.
	 * @throws EntityNotFoundException if no Table2ww found with the given id.
	 */
	Table2ww delete(Integer table2wwId) throws EntityNotFoundException;

    /**
	 * Deletes an existing Table2ww with the given object.
	 *
	 * @param table2ww The instance of the Table2ww to be deleted; value cannot be null.
	 */
	void delete(Table2ww table2ww);

	/**
	 * Find all Table2wws matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table2wws.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Table2ww> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Table2wws matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table2wws.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Table2ww> findAll(String query, Pageable pageable);

    /**
	 * Exports all Table2wws matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Table2wws in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Table2ww.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

