/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.new_vcs_conflicts.bubbledata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Bubble generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`bubble`")
@IdClass(BubbleId.class)
public class Bubble implements Serializable {

    private Integer id;
    private String name;
    private Double lifeExpectency;
    private Double fertilityRate;
    private String region;
    private Double population;
    private Double area;
    private Double density;
    private Integer column9;
    private Table2ww table2ww;

    @Id
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`name`", nullable = false, length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`lifeExpectency`", nullable = true, scale = 4, precision = 12)
    public Double getLifeExpectency() {
        return this.lifeExpectency;
    }

    public void setLifeExpectency(Double lifeExpectency) {
        this.lifeExpectency = lifeExpectency;
    }

    @Column(name = "`fertilityRate`", nullable = true, scale = 4, precision = 12)
    public Double getFertilityRate() {
        return this.fertilityRate;
    }

    public void setFertilityRate(Double fertilityRate) {
        this.fertilityRate = fertilityRate;
    }

    @Column(name = "`region`", nullable = true, length = 20)
    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    @Column(name = "`population`", nullable = true, scale = 4, precision = 12)
    public Double getPopulation() {
        return this.population;
    }

    public void setPopulation(Double population) {
        this.population = population;
    }

    @Column(name = "`area`", nullable = true, scale = 4, precision = 12)
    public Double getArea() {
        return this.area;
    }

    public void setArea(Double area) {
        this.area = area;
    }

    @Column(name = "`density`", nullable = true, scale = 4, precision = 12)
    public Double getDensity() {
        return this.density;
    }

    public void setDensity(Double density) {
        this.density = density;
    }

    @Column(name = "`COLUMN9`", nullable = true, scale = 0, precision = 10)
    public Integer getColumn9() {
        return this.column9;
    }

    public void setColumn9(Integer column9) {
        this.column9 = column9;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`COLUMN9`", referencedColumnName = "`ID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_TABLE2ww_TO_bubble_IDYf0uy`"))
    @Fetch(FetchMode.JOIN)
    public Table2ww getTable2ww() {
        return this.table2ww;
    }

    public void setTable2ww(Table2ww table2ww) {
        if(table2ww != null) {
            this.column9 = table2ww.getId();
        }

        this.table2ww = table2ww;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Bubble)) return false;
        final Bubble bubble = (Bubble) o;
        return Objects.equals(getId(), bubble.getId()) &&
                Objects.equals(getName(), bubble.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName());
    }
}

