/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.new_vcs_conflicts.bubbledata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PostPersist;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * Table2ww generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`TABLE2ww`")
public class Table2ww implements Serializable {

    private Integer id;
    private Integer column2;
    private Table2 table2;
    private List<Bubble> bubbles;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`COLUMN2`", nullable = true, scale = 0, precision = 10)
    public Integer getColumn2() {
        return this.column2;
    }

    public void setColumn2(Integer column2) {
        this.column2 = column2;
    }

    @OneToOne(fetch = FetchType.EAGER, mappedBy = "table2ww")
    @Cascade({CascadeType.SAVE_UPDATE})
    @Fetch(FetchMode.JOIN)
    public Table2 getTable2() {
        return this.table2;
    }

    public void setTable2(Table2 table2) {
        this.table2 = table2;
    }

    @JsonInclude(Include.NON_EMPTY)
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "table2ww")
    @Cascade({CascadeType.SAVE_UPDATE})
    public List<Bubble> getBubbles() {
        return this.bubbles;
    }

    public void setBubbles(List<Bubble> bubbles) {
        this.bubbles = bubbles;
    }

    @PostPersist
    public void onPostPersist() {
        if(table2 != null) {
            table2.setTable2ww(this);
        }
        if(bubbles != null) {
            for(Bubble bubble : bubbles) {
                bubble.setTable2ww(this);
            }
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Table2ww)) return false;
        final Table2ww table2ww = (Table2ww) o;
        return Objects.equals(getId(), table2ww.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

